### ISSUE TITLE
asv cannot use conda environments for conda >= 4.4

### ISSUE THREAD

**Issue by jni** [airspeed-velocity/asv#645]
Since conda 4.4, conda is no longer an executable script, but rather a bash function that shadows the script. (This is to enable the syntax `conda activate env-name`.)

As a consequence, when calling `asv run`, I get the error "Could not find 'conda' in PATH".

The conda executable still exists, but it is shadowed by this function:

```
$ type conda
conda is a function
conda () 
{ 
    if [ "$#" -lt 1 ]; then
        $_CONDA_EXE;
    else
        \local cmd="$1";
        shift;
        case "$cmd" in 
            activate)
                _conda_activate "$@"
            ;;
            deactivate)
                _conda_deactivate "$@"
            ;;
            install | update | uninstall | remove)
                $_CONDA_EXE "$cmd" "$@" && _conda_reactivate
            ;;
            *)
                $_CONDA_EXE "$cmd" "$@"
            ;;
        esac;
    fi
}
```

So it seems we can grab the conda executable from the `_CONDA_EXE` environment variable instead of the `PATH`. I'll have a look at this shortly, but pointers are welcome.

**Comment by pv** [comment]
I think this is already addressed in the master branch at least --- by
not using the conda inside the environment.

**Comment by pv** [comment]
In particular, our CI does not seem to have problems with conda 4.5.

**Comment by jni** [comment]
@pv your conda may not be set up correctly. Specifically, if you try "conda activate env-name", you will get an error suggesting that you add `. $HOME/miniconda3/etc/profile.d/conda.sh` to your bashrc. This will shadow the conda binary.

I can confirm that this is not fixed in master.

**Comment by jni** [comment]
It turns out that I need `CONDA_EXE`, not `_CONDA_EXE`, for some reason I don't understand. Both are defined, but only the former is in `os.environ`.

```console
$ echo $_CONDA_EXE
/home/jni/miniconda3/bin/conda

$ python
Python 3.6.3 |Anaconda, Inc.| (default, Nov  9 2017, 00:19:18) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> '_CONDA_EXE' in os.environ
False
```

**Comment by jni** [comment]
Incidentally, unless I'm missing something, it looks like you are on 4.3.30 on `.travis.yml`?

**Comment by pv** [comment]
I don't think the conda code should assume that conda.sh has been included in bashrc --- certainly IMO that's not "the correct setup", it's just one way to set things up.

conda is upgraded 4.5 by conda update --all on travis.

**Comment by pv** [comment]
What the asv conda code can do is to check whether CONDA_EXE is set --- if yes, it can use that, and if not, fall back to looking things up on PATH.

**Comment by jni** [comment]
@pv yes, I missed the `conda update` command, thanks for pointing me to. And yes, sorry, correct was too strong a word, I'm in a sprint with lots of things pulling at my attention. =) But I would argue that it's the "recommended" way.

**Comment by jakirkham** [comment]
Kind of late here. FWIW the details about how `conda` should be activated for `4.4.0+` is outlined in the release notes.

ref: https://github.com/conda/conda/releases/tag/4.4.0

**Comment by Juanlu001** [comment]
It's been a year since the last release, is there a chance to have one to include this apart from the other changes?
